FROM node:20-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json tsconfig.base.json ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @food-ordering/config build
RUN pnpm --filter @food-ordering/types build
RUN pnpm --filter @food-ordering/database db:generate
RUN pnpm --filter @food-ordering/database build
RUN pnpm --filter @food-ordering/validation build

ARG NEXT_PUBLIC_API_URL="http://34.126.172.168:4000/api"
ARG NEXT_PUBLIC_WS_URL="http://34.126.172.168:4000"
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN pnpm --filter @food-ordering/web build

ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

EXPOSE 3000
CMD ["pnpm", "--filter", "@food-ordering/web", "start"]
